# Starting based off a lab template #
services:
  # Docker in Docker, better isolation than docker.socket #
  dind:
    image: docker:dind
    container_name: dind
    privileged: true # required for dind
    user: root # required for dind, isolated container
    networks:
      jenkins:
        aliases:
          - docker # reachable as tcp://docker:2376
    environment:
      - DOCKER_TLS_CERTDIR=/certs # enforce TLS
    volumes:
      - docker-certs-ca:/certs/ca # CA cert
      - docker-certs-client:/certs/client # client cert
      - docker-build-artefacts:/var/lib/docker # persist build artefacts

  # Jenkins builds dockers via dind #
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: unless-stopped
    depends_on:
      - dind
    networks:
      - jenkins
    security_opt:
      - no-new-privileges:true # block privilege escalation
    environment:
      - DOCKER_HOST=tcp://docker:2376 # point at dind
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1 # enforce TLS
    volumes:
      - docker-certs-client:/certs/client:ro # read-only cert
      - jenkins-data:/var/jenkins_home # persist Jenkins data
      - /usr/bin/docker:/usr/bin/docker # borrow host docker CLI
    ports:
      - "127.0.0.1:8080:8080" # Jenkins web UI, loopback only

volumes:
  docker-certs-ca:
  docker-certs-client:
  docker-build-artefacts:
  jenkins-data:

networks:
  jenkins:
    name: jenkins
